language: python
python:
  - 3.5
sudo: false
cache: pip
services:
  - rabbitmq
install:
  - pip install 'pip>=8.1.1'
  - pip install tox coveralls
script:
  - tox
env:
  - TOXENV=py27-1.8
  - TOXENV=py27-1.9
  - TOXENV=py34-1.8
  - TOXENV=py34-1.9
  - TOXENV=py35-1.8
  - TOXENV=py35-1.9
after_success:
  - coveralls
